# DiscordBotに関する設定
discord:
  # Bot接続に使用するToken
  token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  # Application ID
  applicationID: '000000000000000000000'

# Sesameに関する設定
sesame:
  # APIキー
  apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  # SesameデバイスID
  deviceId: 'xxxxxxxxxxxxxxxxxx'
  # Sesameデバイスシークレット
  secretKey: 'xxxxxxxxxxxxxxxxxx'

# Slackに関する設定
slack:
  # WebHookのURL
  webhook: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'

# デバッグ情報の表示
debug: false
