# DiscordBotに関する設定
discord:
  # Bot接続に使用するToken
  token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  # Application ID
  applicationID: '000000000000000000000'
  # 鍵を操作することができるロールのID
  allowedRoleID: '00000000000000000000'
  # スマートロックのステータスと操作コンポーネントを表示するチャンネルID
  statusChannelID: '0000000000000000000000'
  # 施解錠記録を通知するチャンネルID
  logChannelID: '0000000000000000000000'
  # 開発・運営者向けのより詳細な情報を通知するチャンネルID
  consoleChannelID: '0000000000000000000000'

# Sesameに関する設定
sesame:
  # APIキー
  apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  # SesameデバイスID
  deviceId: 'xxxxxxxxxxxxxxxxxx'
  # Sesameデバイスシークレット
  secretKey: 'xxxxxxxxxxxxxxxxxx'

# Slackに関する設定
slack:
  # WebHookのURL
  webhook: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'

# デバッグ情報の表示
debug: false
